config/routes.rb
ActionController::Routing::Routes.draw do |map|

  map.resources :grading_levels
  map.resources :class_timings
  map.resources :subjects
  map.resources :attendances
  map.resources :employee_attendances
  map.resources :attendance_reports

  map.feed 'courses/manage_course', :controller => 'courses' ,:action=>'manage_course'
  map.feed 'courses/manage_batches', :controller => 'courses' ,:action=>'manage_batches'
  map.resources :courses, :has_many => :batches

  map.resources :batches do |batch|
    batch.resources :exam_groups
    batch.resources :additional_exam_groups
    batch.resources :elective_groups, :as => :electives
  end

  map.resources :exam_groups do |exam_group|
    exam_group.resources :exams, :member => { :save_scores => :post }
  end

 map.resources :additional_exam_groups do |additional_exam_group|
    additional_exam_group.resources :additional_exams , :member => { :save_additional_scores => :post }
  end

  map.root :controller => 'user', :action => 'login'

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id/:id2'
  map.connect ':controller/:action/:id.:format'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password, :role, :old_password, :new_password, :confirm_password

  validates_uniqueness_of :username, :email
  validates_length_of     :username, :within => 1..20
  validates_length_of     :password, :within => 4..40, :allow_nil => true
  validates_format_of     :username, :with => /^[A-Z0-9_]*$/i,
    :message => "must contain only letters, numbers, and underscores"
  validates_format_of     :email, :with => /^[A-Z0-9._%-]+@([A-Z0-9-]+\.)+[A-Z]{2,4}$/i,
    :message => "must be a valid email address"
  validates_presence_of   :email, :role
  validates_presence_of   :password, :on => :create
  
  has_and_belongs_to_many :privileges

  def before_save
    self.salt = random_string(8) if self.salt == nil
    self.hashed_password = Digest::SHA1.hexdigest(self.salt + self.password) unless self.password.nil?

    self.admin, self.student, self.employee = false, false, false

    self.admin    = true if self.role == 'Admin'
    self.student  = true if self.role == 'Student'
    self.employee = true if self.role == 'Employee'
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def check_reminders
    reminders =[]
    reminders = Reminder.find(:all , :conditions => ["recipient = '#{self.id}'"])
    count = 0
    reminders.each do |r|
      unless r.is_read
        count += 1
      end
    end
    return count
  end

  def self.authenticate?(username, password)
    u = User.find_by_username username
    u.hashed_password == Digest::SHA1.hexdigest(u.salt + password)
  end

  def random_string(len)
    randstr = ""
    chars = ("0".."9").to_a + ("a".."z").to_a + ("A".."Z").to_a
    len.times { randstr << chars[rand(chars.size - 1)] }
    randstr
  end

  def role_name
    return "Admin" if self.admin?
    return "Student" if self.student?
    return "Employee" if self.employee?
    return nil
  end
  
  def role_symbols
    prv = []
    privileges.map { |privilege| prv << privilege.name.underscore.to_sym }
   
    if admin?
      return [:admin] + prv
    elsif student?
      return [:student] + prv
    elsif employee?
      return [:employee] + prv
    else
      return prv
    end
  end

  def student_record
    Student.find_by_admission_no(self.username)
  end

  def employee_record
    Employee.find_by_employee_number(self.username)
  end
  
end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController
  before_filter :login_required,:configuration_settings_for_hr
  filter_access_to :all
  before_filter :protect_other_employee_data, :only => [:individual_payslip_pdf]
  prawnto :prawn => {:left_margin => 25, :right_margin => 25}
  
  def add_category
    @categories = EmployeeCategory.find(:all)
    @category = EmployeeCategory.new(params[:category])
    if request.post? and @category.save
      flash[:notice] = "Employee category created"
      redirect_to :controller => "employee", :action => "add_category"
    end
  end
  
  def edit_category
    @category = EmployeeCategory.find(params[:id])
    if request.post? and @category.update_attributes(params[:category])
      flash[:notice] = "Employee category updated"
      redirect_to :action => "add_category"
    end
  end

  def delete_category
    employees = Employee.find(:all ,:conditions=>"employee_category_id = #{params[:id]}")
    category_position = EmployeePosition.find(:all, :conditions=>"employee_category_id = #{params[:id]}")
    if employees.empty? and category_position.empty?
      EmployeeCategory.find(params[:id]).destroy
      @categories = EmployeeCategory.find :all
      flash[:notice]="Successfully deleted!"
      redirect_to :action => "add_category"
    else
      flash[:notice]="Unable to delete!"
      redirect_to :action => "add_category"
    end
  end

  def add_position
    @positions = EmployeePosition.find(:all)
    @categories = EmployeeCategory.find(:all,:order => "name asc")
    @position = EmployeePosition.new(params[:position])
    if request.post? and @position.save
      flash[:notice] = "Employee position created"
      redirect_to :controller => "employee", :action => "add_position"
    end
  end

  def edit_position
    @categories = EmployeeCategory.find(:all)
    @position = EmployeePosition.find(params[:id])
    if request.post? and @position.update_attributes(params[:position])
      flash[:notice] = "Employee position updated"
      redirect_to :action => "add_position"
    end

  end

  def delete_position
    employees = Employee.find(:all ,:conditions=>"employee_position_id = #{params[:id]}")

    if employees.empty?
      EmployeePosition.find(params[:id]).destroy
      @positions = EmployeePosition.find :all
      flash[:notice]="Successfully deleted!"
      redirect_to :action => "add_position"
    else
      flash[:notice]="Unable to delete!"
      redirect_to :action => "add_position"
    end
  end

  def add_department
    @departments = EmployeeDepartment.find(:all)
    @department = EmployeeDepartment.new(params[:department])
    if request.post? and @department.save
      flash[:notice] = "Employee department created"
      redirect_to :controller => "employee", :action => "add_department"
    end
  end

  def edit_department
    @department = EmployeeDepartment.find(params[:id])
    if request.post? and @department.update_attributes(params[:department])
      flash[:notice] = "Employee department updated"
      redirect_to :action => "add_department"
    end
  end

  def delete_department
    employees = Employee.find(:all ,:conditions=>"employee_department_id = #{params[:id]}")
    if employees.empty?
      EmployeeDepartment.find(params[:id]).destroy
      @departments = EmployeeDepartment.find :all
      flash[:notice]="Successfully deleted!"
      redirect_to :action => "add_department"
    else
      flash[:notice]="Unable to delete!"
      redirect_to :action => "add_department"
    end
  end

  def add_grade
    @grades = EmployeeGrade.find(:all)
    @grade = EmployeeGrade.new(params[:grade])
    if request.post? and @grade.save
      flash[:notice] = "Employee grade created"
      redirect_to :controller => "employee", :action => "add_grade"
    end
  end

  def edit_grade
    @grade = EmployeeGrade.find(params[:id])
    if request.post? and @grade.update_attributes(params[:grade])
      flash[:notice] = "Employee grade updated"
      redirect_to :action => "add_grade"
    end
  end

  def delete_grade
    employees = Employee.find(:all ,:conditions=>"employee_grade_id = #{params[:id]}")
    if employees.empty?
      EmployeeGrade.find(params[:id]).destroy
      @grades = EmployeeGrade.find :all
      flash[:notice]="Successfully deleted!"
      redirect_to :action => "add_grade"
    else
      flash[:notice]="Unable to delete!"
      redirect_to :action => "add_grade"
    end
  end

  def add_bank_details
    @bank_details = BankField.find(:all)
    @bank_field = BankField.new(params[:bank_field])
    if request.post? and @bank_field.save
      flash[:notice] = "Bank field created"
      redirect_to :controller => "employee", :action => "add_bank_details"
    end
  end

  def edit_bank_details
    @bank_details = BankField.find(params[:id])
    if request.post? and @bank_details.update_attributes(params[:bank_details])
      flash[:notice] = "Bank details updated"
      redirect_to :action => "add_bank_details"
    end
  end
  def delete_bank_details
    employees = EmployeeBankDetail.find(:all ,:conditions=>"bank_field_id = #{params[:id]}")
    if employees.empty?
      BankField.find(params[:id]).destroy
      @bank_details = BankField.find(:all)
      flash[:notice]="Successfully deleted!"
      redirect_to :action => "add_bank_details"
    else
      flash[:notice]="Unable to delete!"
      redirect_to :action => "add_bank_details"
    end
  end

  def add_additional_details
    @additional_details = AdditionalField.find(:all)
    @additional_field = AdditionalField.new(params[:additional_field])
    if request.post? and @additional_field.save
      flash[:notice] = "Additional field created"
      redirect_to :controller => "employee", :action => "add_additional_details"
    end
  end

  def edit_additional_details
    @additional_details = AdditionalField.find(params[:id])
    if request.post? and @additional_details.update_attributes(params[:additional_details])
      flash[:notice] = "Additional details updated"
      redirect_to :action => "add_additional_details"
    end
  end
  def delete_additional_details
    employees = EmployeeAdditionalDetail.find(:all ,:conditions=>"additional_field_id = #{params[:id]}")
    if employees.empty?
      AdditionalField.find(params[:id]).destroy
      @additional_details = AdditionalField.find(:all)
      flash[:notice]="Successfully deleted!"
      redirect_to :action => "add_additional_details"
    else
      flash[:notice]="Unable to delete!"
      redirect_to :action => "add_additional_details"
    end
  end

  def admission1
    @user = current_user
    @user_name = @user.username
    @employee1 = Employee.find_by_employee_number(@user_name)
    @categories = EmployeeCategory.find(:all,:order => "name asc")
    @positions = []
    @grades = EmployeeGrade.find(:all,:order => "name asc")
    @departments = EmployeeDepartment.find(:all,:order => "name asc")
    @nationalities = Country.all
    @employee = Employee.new(params[:employee])
    @last_admitted_employee = Employee.find(:last,:conditions=>"employee_number != 'admin'")
    @config = Configuration.find_by_config_key('EmployeeNumberAutoIncrement')

    if request.post?

      unless params[:employee][:employee_number].to_i ==0
        @employee.employee_number= "E" + params[:employee][:employee_number].to_s
      end

      if @employee.save
        if params[:employee][:gender] == "true"
          Employee.update(@employee.id, :gender => true)
        else
          Employee.update(@employee.id, :gender => false)
        end

        if params[:employee][:status] == "true"
          Employee.update(@employee.id, :status => true)
        else
          Employee.update(@employee.id, :status => false)
        end

        @user = User.new
        @user.first_name = @employee.first_name
        @user.last_name = @employee.last_name
        @user.username = @employee.employee_number.to_s
        @user.password = @employee.employee_number.to_s + "123"
        @user.role = 'Employee'
        @user.email = "noreply" + @employee.employee_number.to_s + "@fedena.com"
        @user.save
        
        flash[:notice] = "Employee #{@employee.first_name} record saved"
        redirect_to :controller =>"employee" ,:action => "admission2", :id => @employee.id
      end
    end
  end

  def update_positions
    category = EmployeeCategory.find(params[:category_id])
    @positions = EmployeePosition.find_all_by_employee_category_id(category.id)
    render :update do |page|
      page.replace_html 'positions1', :partial => 'positions', :object => @positions  
    end
  end

  def edit1
    @categories = EmployeeCategory.find(:all,:order => "name asc")
    @positions = EmployeePosition.find(:all)
    @grades = EmployeeGrade.find(:all,:order => "name asc")
    @departments = EmployeeDepartment.find(:all,:order => "name asc")
    @employee = Employee.find(params[:id])
    if request.post? and @employee.update_attributes(params[:employee])
      if params[:employee][:gender] == "true"
        Employee.update(@employee.id, :gender => true)
      else
        Employee.update(@employee.id, :gender => false)
      end

      if params[:employee][:status] == "true"
        Employee.update(@employee.id, :status => true)
      else
        Employee.update(@employee.id, :status => false)
      end

      flash[:notice] = "Employee #{@employee.first_name} general information updated"
      redirect_to :controller =>"employee" ,:action => "profile", :id => @employee.id
    end
  end

  def edit_personal
    @nationalities = Country.all
    @employee = Employee.find(params[:id])
    if request.post? and @employee.update_attributes(params[:employee])
      flash[:notice] = "Employee #{@employee.first_name} personal information updated"
      redirect_to :controller =>"employee" ,:action => "profile", :id => @employee.id
    end
  end

  def admission2
    @countries = Country.find(:all)
    @employee = Employee.find(params[:id])

app/views/employee/_equal_to_select.erb
<%= select :adv_search, :joining_date_year, (1990..2010),{:prompt=>"Select"},
{:onChange => "#{remote_function(:url => {:action => "doj_equal_to_update"},
        :with => "'year='+value"
        )}"}
%>

app/views/employee/_greater_than_doj_select.erb
<%= hidden_field :search, :joining_date_lt, :value=>@start_date %>
<%= hidden_field :search, :joining_date_gt, :value=>@end_date %>

app/views/employee/_less_than_dob_select.erb
<%= hidden_field :search, :date_of_birth_gt, :value=>@start_date %>
<%= hidden_field :search, :date_of_birth_lt, :value=>@end_date %>

app/views/employee/_less_than_doj_select.erb
<%= hidden_field :search, :joining_date_gt, :value=>@start_date %>
<%= hidden_field :search, :joining_date_lt, :value=>@end_date %>

app/views/employee/_less_than_select.erb
<%= select :adv_search, :joining_date_year, (1990..2010),{:prompt=>"Select"},
{:onChange => "#{remote_function(:url => {:action => "doj_less_than_update"},
        :with => "'year='+value"
        )}"}
%>

app/views/employee/_one_click_approve.html.erb
<%unless @dates.empty? %>
  <div id="submit-button" class ="approve">
      <%= link_to "► Approve", {:controller=>"employee", :action=>"one_click_approve_submit",:date => @salary_date } %>
  </div>
<% else%>
  <div id="submit-button" class ="approved">
     Already approved!
  </div>
<% end %>

app/views/employee/_subjects.html.erb
   <div class="label-field-pair">
      <label for="subject_name">Subject</label>
        <div class="text-input-bg"><%= select :subject_assignment, :subject_id, @subjects.map { |s| [s.name, s.id] },
          {:prompt => "Select subject"},
          {:onChange => "#{remote_function(:url => {:action => "select_department"}, :with => "'subject_id='+value")}"} %>
</div>
   </div>

app/views/employee/_update_employee_payslip.html.erb
<ul class="item-list">
  <!-- <li class="heading"><%= @employee.full_name %></li> -->
  <li class="heading">Payslip generated on: <%= @salary_date %></li>
</ul>
<div class="prev-next-links">
     <div id="register">
      <div class="header">
        <div class="prev">
         <%= link_to_remote '◄',:url => {:action => 'update_employee_payslip', :department_id => @department.id, :employee => @prev_employee.id, :salary_date=> @salary_date }%>
        </div>
        <div class="month">
          <%=  @employee.full_name %>
        </div>
        <div class="next">
            <%= link_to_remote '►',:url => {:action => 'update_employee_payslip', :department_id => @department.id, :employee => @next_employee.id, :salary_date=> @salary_date }%>
        </div>
        <div class="extender"></div>
      </div>
    </div>
  </div>

<ul class="item-list">
    <li class="heading1">Salary</li>
  <% @monthly_payslips.each do |mp| %>
    <% category = PayrollCategory.find(mp.payroll_category_id) %>
    <% @emp = Employee.find(mp.employee_id) %>
    <% unless category.is_deduction == true %>
    <li class="list<%=cycle('odd', 'even')%>">
      <div class="item-name"><%= category.name  %> </div>
      <div class="item-edit"><span class="currency-type"><%= @currency_type %></span> <%= mp.amount %></div>
    </li>
    <% end %>
  <% end %>
      <% unless @individual_payslip_category.empty? %>

    <% @individual_payslip_category.each do |pc| %>
      <%if  pc.is_deduction == false %>
      <li class="list<%=cycle('odd', 'even')%>">
        <div class="item-name"><%= pc.name %></div>
               <div class="item-edit"><span class="currency-type"><%= @currency_type %></span> <%= pc.amount %></div>
      </li>
      <% end %>
    <% end %>
  <% end %>
      <li class="list<%=cycle('odd', 'even')%>">
    <div class="item-name"><b>Total Salary </b></div>
    <div class="item-edit"><b><span class="currency-type"><%= @currency_type %></span> <%=@net_non_deductionable_amount  %></b></div>
  </li>
</ul>

<ul class="item-list">
  <li class="heading1">Deductions</li>
  <% @monthly_payslips.each do |mp| %>
    <% category = PayrollCategory.find(mp.payroll_category_id) %>
    <% @emp = Employee.find(mp.employee_id) %>
    <% unless category.is_deduction == false %>
    <li class="list<%=cycle('odd', 'even')%>">
      <div class="item-name"><%= category.name  %></div>
      <div class="item-edit"><span class="currency-type"><%= @currency_type %></span> <%= mp.amount %></div>
    </li>
    <% end %>
  <% end %>
      <% unless @individual_payslip_category.empty? %>

    <% @individual_payslip_category.each do |pc| %>
      <%if  pc.is_deduction == true %>
      <li class="list<%=cycle('odd', 'even')%>">
        <div class="item-name"><%= pc.name %></div>
               <div class="item-edit"><span class="currency-type"><%= @currency_type %></span> <%= pc.amount %></div>
      </li>
      <% end %>
    <% end %>
  <% end %>
       <li class="list<%=cycle('odd', 'even')%>">
      <div class="item-name"><b>Total Deductions </b></div>
      <div class="item-edit"><span class="currency-type"><b><%= @currency_type %></b></span> <b><%=@net_deductionable_amount %></b></div>
    </li>
</ul>

<ul class="item-list">
  <li class="heading1">Total</li>
  <li class="listeven">
    <div class="item-name"><b>Net Salary </b></div>
    <div class="item-edit"><span class="currency-type"><b><%= @currency_type %></b></span> <b><%=@net_amount%></b></div>
  </li>
</ul>
<div class="pdf_button"><%= link_to "► PDF report",   {:action => "department_payslip_pdf", :department=>@department.id,:salary_date=> @salary_date, :format => 'pdf'}, :target => '_blank' %>
</div>
<% if permitted_to? :delete_payslip, :payroll %>
<div class="edit-delete-link">
  <%= link_to "delete",{:controller => "employee", :action => "delete_payslip", :id=> @emp.id, :id2=>@salary_date}, :confirm=>"Are you sure?" %>
</div>
<% end %>

app/views/employee/_view_rep_manager.erb
<div id="new_profile_info_top">
  <div class="profile_info_label_top">Reporting Manager</div>
  <div class="profile_info_text_top">
    <%=  @reporting_manager%>
  </div>

</div>



<div class="extender"></div>
<div class="edit-pdf-group">
  <% if permitted_to? :change_reporting_manager, :employee %>
    <div class="edit">
      <%= link_to "► Edit",  :controller => "employee", :action => "change_reporting_manager", :id =>@employee.id %>
    </div>
  <%end%>
</div>

app/views/employee/change_to_former.html.erb
<div id="content-header">
    <img src="/images/HR/show_hr.png" alt="" />
  <h1>Students</h1>
  <h3>Leaving school</h3>
  <div id="app-back-button">
   <%= link_to_function image_tag("/images/buttons/back.png",:border => 0), "history.back()" %>
  </div>
</div>

<div id="page-yield">

  <div id="student-details">
<h4> <%= @employee.first_name %> | Employee no : <%= @employee.employee_number %> | Department : <%= @employee.employee_department.name %> </h4>
  </div>

  <div class="extender"> </div>

  <div id="remove-student">
    <p>For employees leaving the school, use this option to remove them from the list of active employees and place them in the former employees list.</p>

    <% form_for :remove do |f| %>
      <div class="label-field-pair">
        <label for="remove_descr">Reason for leaving</label>
        <div class="text-input-bg"><%= f.text_field :status_description %></div>
      </div>

      <div id="submit-button">
        <%= submit_tag '► Remove',:class=>'submit_button' %>
      </div>

    <% end %>
  </div>

</div>

app/views/employee/edit_privilege.html.erb
<div id="content-header">
  <img src="/images/HR/show_hr.png" alt="" />
  <h1>User Privileges</h1>
  <h3>Set Privilege</h3>
  <div id="app-back-button">
    <%= link_to_function image_tag("/images/buttons/back.png",:border => 0), "history.back()" %>
  </div>
</div>



<div class="label_field_pair"><label>Set privileges for <%= @user.first_name.capitalize+" "+@user.last_name.capitalize %></label></div>
<div id="list_content">
  <div id="list">
    <div class="sel-list">
      Select: <%= link_to_function 'All', "$$('input.right').each(function(checkbox) { checkbox.checked = true; });" %>,
      <%= link_to_function 'None', "$$('input.right').each(function(checkbox) { checkbox.checked = false; });" %>
    </div>


    <% form_for :user do |form| %>
      <% for privilege in Privilege.find(:all) %>
        <%    hr = Configuration.find_by_config_value("HR") %>
        <%  finance = Configuration.find_by_config_value("Finance") %>
        <%  if hr.nil?  %>
          <% if privilege.id ==9 or  privilege.id ==17 or privilege.id ==19 %>
            <% next %>
          <% end %>
        <% end %>
        <%  if finance.nil?  %>
          <% if privilege.id ==14 or  privilege.id ==18 %>
            <% next %>
          <% end %>
        <% end %>
        <div class="name_list<%=cycle('odd', 'even')%>"><li>
            <label><%= check_box_tag "user[privilege_ids][]", privilege.id, @user.privileges.include?(privilege),:class=>'right'%>
              <div class="att_list_names"> <%= privilege.name.underscore.gsub(/_/, ' ').capitalize %> </div> </label>
          </li></div>
      <% end %>
      <div class="user_submit_button1">
        <%= submit_tag "", :name => "commit", :value => "► Update" %>
      </div>
    <% end %>
  </div>
</div>

app/views/employee/employee_management.html.erb
<div id="content-header">
  <img src="/images/HR/show_hr.png" alt="" />
  <h1>Employee Management</h1>
  <h3>Manage all employees </h3>
  <div id="app-back-button">
     <%= link_to_function image_tag("/images/buttons/back.png",:border => 0), "history.back()" %>
  </div>
</div>

<div id="page-yield">
  <div id="box">
  <div class="link-box">
    <div class="link-heading"><%= link_to "Employee admission", :controller=>"employee", :action=>"admission1" %></div>
    <div class="link-descr">Employee admissions form</div>
  </div>

  <div class="link-box">
    <div class="link-heading"><%= link_to "Employee Subject Association", :controller=>"employee", :action=>"subject_assignment"%></div>
    <div class="link-descr">Assign an employee with one or more subjects</div>
  </div>
  </div>

</div>

app/views/employee/payslip_approve.erb
<div id="content-header">
  <img src="/images/HR/show_hr.png" alt="" />
  <h1>Employee Payslip</h1>
  <h3>Approve Payslip</h3>
  <div id="app-back-button">
    <%= link_to_function image_tag("/images/buttons/back.png",:border => 0), "history.back()" %>
  </div>
</div>
<div id="page-yield">
  <div class="box">
    <div class="label-field-pair">
    <label for="salary_date">Salary Month</label>
    <div class="text-input-bg"><%= select :one_click_payslip, :salary_date, @salary_dates.map {|c| [c.salary_date.strftime("%B %Y"),c.salary_date.strftime("%Y-%m-%d")]},
                                              {:prompt => 'Select a month'},
                                              {:onChange => "#{remote_function(:url => {:action=> "one_click_approve"},
                                              :with => "'salary_date='+value")}"} %></div>
    </div>

<div id ="approve"> </div>
</div>
  </div>